[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pyspark-ai"
version = "0.1.17"
description = "English SDK for Apache Spark"
authors = ["Gengliang Wang <gengliang@apache.org>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/databrickslabs/pyspark-ai"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

[tool.poetry.dependencies]
# default required dependencies
python = "^3.8.1"
pydantic = "^1.10.10"
openai = "^0.27.8"
langchain = ">=0.0.271,<0.1.0"
pygments = "^2.15.1"

# optional dependencies, opted into by groups

# dependencies for create
requests = { version = "^2.31.0", optional = true }
tiktoken = { version = "0.4.0", optional = true }
beautifulsoup4 = { version = "^4.12.2", optional = true }
google-api-python-client = { version = "^2.90.0", optional = true }

# dependencies for plot
pandas = { version = ">=1.0.5", optional = true, extras = ["all"]}
grpcio = { version = ">=1.56.0", optional = true}
plotly = { version = "^5.15.0", optional = true }
pyarrow = { version = ">=4.0.0", optional = true }

# dependencies for vector-search
grpcio-status = { version = ">=1.56.0", optional = true }
faiss-cpu = { version = "^1.7.4", optional = true }
sentence-transformers = { version = "^2.2.2", optional = true }
torch = { version = ">=2.0.0, !=2.0.1", optional = true }

[tool.poetry.group.dev.dependencies]
pyspark = "^3.4.0"
babel = "^2.12.1"
chispa = "^0.9.2"

[tool.poetry.group.lint.dependencies]
flake8 = "^6.0.0"
black = "^23.7.0"

[tool.poetry.extras]
create = ["requests", "tiktoken", "beautifulsoup4", "google-api-python-client"]
plot = ["pandas", "grpcio", "plotly", "pyarrow"]
vector-search = ["grpcio-status", "faiss-cpu", "sentence-transformers", "torch"]
